### ISSUE TITLE
[Bug] Unable to start a workflow in production build

### ISSUE THREAD

**Issue by rubbishjunk** [temporalio/nextjs-temporal-one-click-template#3]
### What are you really trying to do?

Trying to run this example in nextjs production build

### Describe the bug

Unable to start the workflow
```
[ERROR] Failed to activate workflow {
  sdkComponent: 'worker',
  taskQueue: 'ecommerce-oneclick',
  runId: 'be218417-0e82-4ca4-ac40-cdfde5f63f19',
  error: /src/nextjs-temporal-one-click-template/workflow-bundle-99720e57275f2eaee496.js:3816
          throw new TypeError(`Failed to initialize workflow of type '${activator.info.workflowType}': ${details}`);
          ^

  TypeError: Failed to initialize workflow of type 'd': no such function is exported by the workflow bundle
      at Object.initRuntime (/src/nextjs-temporal-one-click-template/node_modules/@temporalio/workflow/src/worker-interface.ts:155:10)
      at evalmachine.<anonymous>:1:18
      at Script.runInContext (node:vm:134:12)
      at Object.runInContext (node:vm:282:6)
      at Proxy.<anonymous> (/src/nextjs-temporal-one-click-template/node_modules/@temporalio/worker/lib/workflow/reusable-vm.js:94:50)
      at ReusableVMWorkflowCreator.createWorkflow (/src/nextjs-temporal-one-click-template/node_modules/@temporalio/worker/lib/workflow/reusable-vm.js:121:24)
      at handleRequest (/src/nextjs-temporal-one-click-template/node_modules/@temporalio/worker/lib/workflow/workflow-worker-thread.js:42:35)
      at MessagePort.<anonymous> (/src/nextjs-temporal-one-click-template/node_modules/@temporalio/worker/lib/workflow/workflow-worker-thread.js:92:38)
      at [nodejs.internal.kHybridDispatch] (node:internal/event_target:786:20)
      at exports.emitMessage (node:internal/per_context/messageport:23:28),
  workflowExists: false
}
```

### Minimal Reproduction

1. build and start the worker
    1. `npm run build:temporal`
    1. `npm run start:worker`
1. build and start nextjs
    1. `npm run build:nextjs`
    1. `npm run start`
1. click on buy now in the UI
1. got `no such function is exported by the workflow bundle` error above
1. in temporal ui
    <img width="1318" alt="temp" src="https://github.com/user-attachments/assets/26f16fd4-9e53-413a-9087-d984701a6f6a">

### Environment/Versions

- OS and processor: mac m3 pro
- Temporal Version: `1.23.0`, sdk version: `^1.10.0` 
- Are you using Docker or Kubernetes or building Temporal from source?: temporal docker compose postgres

**Comment by rclmenezes** [comment]
Yup this is caused by:
https://github.com/vercel/next.js/issues/74332#issuecomment-2620236458

The only options I see are:
- Don't minimize your Next.js project on the server
- Package your workflows separately without mangling function names. Have Next use the pre-built package
- Patch the typescript SDK such that we can customize the workflowType
- Import your workflows as an object that can be imported in the client with the same names (edit -- never mind, this doesn't work either)

For now, I'm going with option 1. This is what my next config looks like:

```
export default {
  webpack: (config) => {
    if (config.name === "server") {
      // Disable minification for server builds to avoid temporal build errors
      config.optimization.minimize = false;
    }
    return config;
  },
};
```

**Comment by HalfdanJ** [comment]
Came here because i was looking what the "official" next.js sample code did from temporal, your solution above worked. Would be great to update this sample, and also to update the tutorial to point it out https://learn.temporal.io/tutorials/typescript/build-one-click-order-app-nextjs/
